### PR TITLE
Upgrade to svelte 4 x x

### PR DESCRIPTION
**Pull request by MelleD**
Upgrade to svelte 4 x x

### CODE REVIEW

**Comment by Alia5** [comment]
Hey @MelleD 

Why upgrade to Svelte 4 when 5 is on the horizon and pretty darn stable?

You might want to checkout: https://github.com/Alia5/lovelace-expander-card/pull/41

**Comment by MelleD** [comment]
Hey @Alia5,

my understanding is svelte 5 is not production ready, right?

**Comment by MelleD** [comment]
Hey @Alia5,

I upgraded to Svelte 5.x.x and same performance issue. Svelte 3.x.x was much faster.
I also tried your new release and with the new release I observed the same thing: the card creation now take longer to load.

**Comment by Alia5** [comment]
@MelleD 
> my understanding is svelte 5 is not production ready, right?

Officially in RC. The release shouldn't be too far off.
breaking API changes will almost certainly not occur at this point.
Bugs are mostly minor technicalities or fringe cases. 

> a) Why did you switch to pnpm?

It's my currently preferred node package manager. Nothing to it.

> b) Do you have good experience with vite?

WDYM exactly? But yes. I like Vite and have been using it for a few years now, both hobby and professional use

> I upgraded to Svelte 5.x.x and same performance issue. Svelte 3.x.x was much faster.

Have you dug any deeper?
I don't experience any issues here.

**Comment by MelleD** [comment]
Professionally, I am more concerned with backend development and less with frontend. That's why I like to hear what the reasons/advantages/disadvantages are from experienced developers (for a and b). More out of curiosity and to learn.

> Have you dug any deeper?
I don't experience any issues here.

It's easy to reproduce. Let me make MRE over the weekend what is reusable for testing.
Yes I looked into it, but how I said currently no clue what is the issue, because the code is not changed. For Svelte 4 and 5.

IMHO one improvement could be to cache the cards and no (re)create it everytime, but this solves not the issue with the initial load.
With the previous version the initial load was very fast and I didn't see the "Loading ..." label. Now I see this a lot and the UI needs sometime to load all expanders.

Thanks for help

**Comment by MelleD** [comment]
Here a complete Dashboard to show it:
```
---
views:
  - title: Test
    path: testo
    badges: []
    cards:
      - type: custom:expander-card
        title: Expander
        expanded: true
        title-card:
          type: entities
          entities:
            - entity: sun.sun
              name: This is an entity with a very long name that breaks things
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        expanded: true
        title-card:
          type: entities
          entities:
            - entity: sun.sun
              name: This is an entity with a very long name that breaks things
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        expanded: true
        title-card:
          type: entities
          entities:
            - entity: sun.sun
              name: This is an entity with a very long name that breaks things
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        expanded: true
        title-card:
          type: entities
          entities:
            - entity: sun.sun
              name: This is an entity with a very long name that breaks things
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
      - type: custom:expander-card
        title: Expander
        expanded: true
        title-card:
          type: entities
          entities:
            - entity: sun.sun
              name: This is an entity with a very long name that breaks things
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things

```

**Comment by MelleD** [comment]
Bildschirmfoto 2024-09-27 um 17 27 30


And I have a small glitch in the UI ( could me issue on my side have to test again)

Bildschirmfoto 2024-09-27 um 17 30 12

**Comment by MelleD** [comment]
So I would like to try to cache this cards:

```
            {#each config.cards as card (card)}
                <Card hass={hass} config={card} type={card.type} marginTop={config['child-margin-top']}/>
            {/each}
```

But no idea how ;)

**Comment by Alia5** [comment]
Look here: https://github.com/Alia5/lovelace-expander-card/commit/dc04a443a235202f021e5e60e35d8c63f403278f

**Comment by MelleD** [comment]
> Look here: [dc04a44](https://github.com/Alia5/lovelace-expander-card/commit/dc04a443a235202f021e5e60e35d8c63f403278f)

Thanks I will try that, but one question it not better or possible to cache the Card instance in the ExpanderCard directly?
so this one
```
<Card hass={hass} config={card} type={card.type} marginTop={config['child-margin-top']}/>
            {/each}
```

**Comment by MelleD** [comment]
> Look here: [dc04a44](https://github.com/Alia5/lovelace-expander-card/commit/dc04a443a235202f021e5e60e35d8c63f403278f)

But cool much better :) Thanks a lot good job

**Pull request closed without merging**
